//! The composed command line's one generated file: what goes in it, what it
//! says, and the operation that rewrites it.
//!
//! `render` is the text this file always starts and ends with — the `//
//! @generated` banner, one `("<name>", <crate>::task())` line per imported
//! task, and the call into `rituals::run`. Both forms of the operation write
//! that text only when it actually differs from what is already on disk,
//! which is what makes running the operation twice with nothing changed in
//! between leave the file's own modification time untouched, not merely its
//! bytes unchanged.
//!
//! The operation comes in two forms that share one rendering path:
//! [`regenerate`], for a task with no run of its own, and
//! [`regenerate_recording`], for one that is already inside a
//! [`crate::rollback::attempt`] and needs the file put back with everything
//! else if the run fails.

mod entry;
mod identifier;

use std::fmt::{self, Write as _};
use std::path::{Path, PathBuf};

pub use entry::Entry;
use identifier::{hides_a_crate_the_file_names, render_identifier};
use rituals::{CommandLine, Failure, Name, Outcome, report};

use crate::metadata::Metadata;
use crate::rollback::Changes;
use crate::rust_name::extern_identifier;
use crate::{metadata, top_level};

/// Renders a composed command line's generated `main.rs`.
///
/// `package_name` names the composed CLI crate this file belongs to — it
/// appears only in the module doc comment; the rest of the file reads its
/// own identity — package name, bin name and version — from
/// `rituals::identity!()` at compile time. `entries` are emitted in
/// the order given, one per line, with no wrapping and no sorting: the order
/// is the caller's, because it is the order
/// `[package.metadata.ritual] tasks = [...]` names them in, and keeping the
/// two in step is what makes a diff of the generated file boring.
///
/// The rendered file names `rituals` and nothing else — a composed CLI
/// crate depends on the framework crate directly, not on this one.
///
/// # Examples
///
/// ```
/// use rituals_compose::generated_file::{Entry, render};
///
/// let rendered = render("rituals-cli", &[Entry::new("new", "new")]);
/// assert!(rendered.starts_with("// @generated by ritual — do not edit.\n"));
/// assert!(rendered.contains("    rituals::run(\n"));
/// assert!(rendered.contains("            (\"new\", new::task()),\n"));
/// ```
#[must_use]
pub fn render(package_name: &str, entries: &[Entry]) -> String {
    let mut output = String::new();

    output.push_str("// @generated by ritual — do not edit.\n");
    output.push_str("//\n");
    output.push_str(
        "// Every task named in [package.metadata.ritual] tasks in this crate's Cargo.toml\n",
    );
    output
        .push_str("// is handed to the framework below. Change that list, then run this command\n");
    output.push_str("// line's `regenerate` task.\n");
    output.push_str("//\n");
    output.push_str(
        "// If this file stopped compiling because a task's dependency was removed before\n",
    );
    output.push_str(
        "// its entry was dropped from that list: put the dependency back, drop the entry,\n",
    );
    output.push_str("// run `regenerate`, then remove the dependency.\n");
    output.push('\n');
    // A String's Write impl never returns Err, so the result is discarded
    // deliberately rather than propagated.
    let _ = writeln!(output, "//! The composed `{package_name}` command line.");
    output.push('\n');
    output.push_str(
        "// rustfmt is skipped here on purpose: this file has to be reproducible byte for\n",
    );
    output.push_str(
        "// byte, and that is only true while one thing decides its formatting. Predicting\n",
    );
    output.push_str("// where rustfmt breaks a line is a moving target, not a contract.\n");
    output.push_str("#[rustfmt::skip]\n");
    output.push_str("fn main() -> std::process::ExitCode {\n");
    output.push_str("    rituals::run(\n");
    output.push_str("        rituals::identity!(),\n");
    render_entries(&mut output, entries);
    output.push_str("    )\n");
    output.push_str("}\n");

    output
}

/// A key for `[package.metadata.ritual] tasks` that the generated file can
/// compile with.
///
/// [`TaskKey::new`] is the only way to make one, and it refuses a key whose
/// extern-crate identifier is `std` or `core`, which the file reaches by
/// those names: a dependency under either stands in for Rust's own crate. A
/// command line that no longer compiles cannot run the command that would
/// take the key back out, so every writer of the list takes a `TaskKey`
/// rather than a [`Name`], and a writer that skips the rule does not
/// compile. The rule is the same one the resolver asks of a list written by
/// hand, so a key `import` refuses is one `regenerate` refuses.
///
/// # Examples
///
/// ```
/// use rituals::Name;
/// use rituals_compose::generated_file::TaskKey;
///
/// let key = TaskKey::new(Name::new("lint")?)?;
/// assert_eq!(key.as_str(), "lint");
///
/// let refused = TaskKey::new(Name::new("std")?);
/// assert!(refused.is_err());
/// # Ok::<(), Box<dyn std::error::Error>>(())
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TaskKey(Name);

impl TaskKey {
    /// Makes `name` a task key, once it is known to hide no crate the
    /// generated file names.
    ///
    /// # Errors
    ///
    /// Returns a [`Failure`] naming the key and the crate it would hide.
    pub fn new(name: Name) -> Result<Self, Failure> {
        ensure_key_hides_no_crate(&name)?;
        Ok(Self(name))
    }

    /// The key as the [`Name`] it was made from.
    #[must_use]
    pub const fn as_name(&self) -> &Name {
        &self.0
    }

    /// The key as text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        self.0.as_str()
    }

    /// The [`Name`] this key was made from.
    #[must_use]
    pub fn into_name(self) -> Name {
        self.0
    }
}

impl fmt::Display for TaskKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.0, formatter)
    }
}

impl AsRef<Name> for TaskKey {
    fn as_ref(&self) -> &Name {
        &self.0
    }
}

impl AsRef<str> for TaskKey {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

/// Refuses a task key the generated file could not compile with: one whose
/// extern-crate identifier is `std` or `core`.
///
/// One rule for [`TaskKey::new`], which every writer of a key goes through,
/// and for the resolver that reads the list, so the two cannot disagree.
///
/// # Errors
///
/// Returns a [`Failure`] naming the key and the crate it would hide.
pub(crate) fn ensure_key_hides_no_crate(key: &Name) -> Outcome {
    let identifier = extern_identifier(key.as_str());
    if hides_a_crate_the_file_names(&identifier) {
        return Err(Failure::new(format!(
            "`{key}` would hide Rust's own `{identifier}` crate, which the generated command \
             line is built on, and it would no longer compile; give this task another key"
        )));
    }
    Ok(())
}

/// Appends the second argument to `rituals::run` — an empty array on
/// one line, or one indented entry per line — to `output`.
fn render_entries(output: &mut String, entries: &[Entry]) {
    if entries.is_empty() {
        output.push_str("        [],\n");
        return;
    }

    output.push_str("        [\n");
    for entry in entries {
        let identifier = render_identifier(&entry.extern_crate);
        let _ = writeln!(
            output,
            "            (\"{}\", {identifier}::task()),",
            entry.command
        );
    }
    output.push_str("        ],\n");
}

/// Rewrites `command_line`'s composed CLI's generated file from its current
/// imports, reporting what it did.
///
/// The whole operation: read the current directory, fetch the resolved
/// dependency graph, resolve the task list and locate the project on it,
/// [`render`] the text, and write it if it changed. Lives here, beside
/// [`render`], rather than in either task that calls it — both `create` and
/// `regenerate` run this same path, and neither can depend on the other, so
/// the one place both can reach it without a dependency between them is the
/// module that already renders the file both act on. `render` is the text;
/// this is the operation; `new` is the caller that genuinely wants only the
/// first, for a fresh project's generated file before it has any imports at
/// all.
///
/// Takes the whole [`CommandLine`] rather than a package name: in this
/// repository's own composed CLI, the package is `rituals-cli` and the bin
/// is `ritual`, so a bare `&str` parameter would accept the wrong one
/// silently. And `regenerate` is one of the two writing tasks that has to
/// weigh a name it is about to write against the *running* command line's
/// own top level, not only against this project's manifest — the same
/// commands its own identity's package name cannot answer alone — so it
/// needs the whole command line, not only the identity inside it.
///
/// # Errors
///
/// Returns a [`rituals::Failure`] naming whichever step failed: reading the
/// current directory, fetching or resolving the metadata, a task name that
/// is already a top-level command of `command_line`, or reading or writing
/// the file.
///
/// # Examples
///
/// ```
/// use rituals::{CommandLine, Outcome, Task, clap};
/// use rituals_compose::generated_file;
///
/// /// Rewrites this project's generated file from its current imports.
/// #[derive(clap::Args)]
/// struct Arguments {}
///
/// fn run(command_line: &CommandLine, _arguments: Arguments) -> Outcome {
///     generated_file::regenerate(command_line)
/// }
///
/// // Never invoked here: running it needs a real project on disk and a
/// // `cargo metadata` call. This shows the whole of a task built on it.
/// let _task = Task::receiving_command_line("rewrite the generated task list", run);
/// ```
pub fn regenerate(command_line: &CommandLine) -> Outcome {
    let package_name = command_line.identity().package_name();

    let current_dir = std::env::current_dir()
        .map_err(|error| Failure::new("reading the current directory failed").caused_by(error))?;
    let document = metadata::fetch(&current_dir)?;

    document.ensure_runs_in_its_own_project(package_name, "regenerate", "")?;
    let regenerated = regenerate_from(command_line, &document, write_to_disk)?;

    report(regenerated.to_string());
    Ok(())
}

/// Rewrites the generated file as a step of a run, so a later failure puts
/// it back.
///
/// The run is one already inside
/// [`rollback::attempt`](crate::rollback::attempt). The file is rewritten from `command_line`'s composed CLI's current
/// imports, and a run that fails afterwards puts it back with everything
/// else the run changed.
///
/// It does what [`regenerate`] does, through the same rendering, with two
/// differences. The file is written through `changes`, and only when its
/// content differs, so an unchanged file is neither touched nor recorded.
/// And it prints nothing: it returns a [`Regenerated`], whose `Display` is
/// the line [`regenerate`] reports, so the caller decides when to say it.
///
/// `directory` is where `cargo metadata` runs, as [`regenerate`] runs it
/// from the current directory; any directory of the project will do.
/// `cargo metadata` creates or rewrites `Cargo.lock` when it is missing or
/// behind the manifests, so it runs through
/// [`metadata::fetch_recording`], which
/// records the workspace root's lockfile in `changes` first, whichever
/// directory `directory` is. The caller has already checked that this
/// command line runs inside its own project; this does not repeat the check.
///
/// # Errors
///
/// Returns a [`Failure`] for any reason [`regenerate`] would, and when
/// Cargo finds no workspace for `directory`.
///
/// # Examples
///
/// ```no_run
/// use std::path::Path;
///
/// use rituals::{CommandLine, Failure, Identity};
/// use rituals_compose::generated_file;
/// use rituals_compose::rollback::{self, Wording};
///
/// # let command_line = CommandLine::from_dispatch(
/// #     Identity::from_macro_expansion("demo-ritual", "ritual", "0.1.0"),
/// #     [],
/// #     ["regenerate"],
/// # );
/// // Needs a real project on disk and runs `cargo metadata` in it, so this
/// // example is `no_run`.
/// let directory = Path::new("/path/to/the/workspace");
/// let wording = Wording::project(directory, "running `cargo ritual remove lint` again");
/// let regenerated = rollback::attempt(wording, |changes| {
///     // ... edits that must be undone with the generated file, then:
///     let regenerated =
///         generated_file::regenerate_recording(changes, &command_line, directory)?;
///     // ... more steps, any of which may fail.
///     Ok::<_, Failure>(regenerated)
/// })?;
/// println!("{regenerated}");
/// # Ok::<(), Failure>(())
/// ```
pub fn regenerate_recording(
    changes: &mut Changes,
    command_line: &CommandLine,
    directory: &Path,
) -> Result<Regenerated, Failure> {
    let document = metadata::fetch_recording(changes, directory)?;

    regenerate_from(command_line, &document, |path, content| {
        changes.write(path, content)
    })
}

/// What [`regenerate`] and [`regenerate_recording`] have in common: resolve
/// the task list, check each name is free at the top level, locate the
/// project, render, and write only if the file's content changes, with
/// whatever `write` does to put bytes on disk.
fn regenerate_from(
    command_line: &CommandLine,
    document: &Metadata,
    write: impl FnOnce(&Path, &str) -> Result<(), Failure>,
) -> Result<Regenerated, Failure> {
    let package_name = command_line.identity().package_name();

    let entries = document.resolve_task_list(package_name)?;
    for entry in &entries {
        top_level::ensure_command_is_free(command_line, entry.command())?;
    }
    let project = document.locate_project(package_name)?;

    let rendered = render(package_name, &entries);
    let outcome = write_with(project.binary_src_path, &rendered, write)?;

    let relative_path = project
        .binary_src_path
        .strip_prefix(project.workspace_root())
        .unwrap_or(project.binary_src_path)
        .to_path_buf();

    Ok(Regenerated {
        relative_path,
        outcome,
        imported: imported_label(&entries),
    })
}

/// What a regeneration did to the generated file, and which tasks it
/// mounts.
///
/// Its `Display` is the one line [`regenerate`] reports: `updated
/// src/main.rs (tasks: ritual, hello)` when the file was written, or
/// `src/main.rs is already up to date (tasks: ritual, hello)` when it
/// already held exactly that content. The path is relative to the workspace
/// root.
///
/// # Examples
///
/// ```no_run
/// use rituals::CommandLine;
/// use rituals_compose::generated_file;
/// use rituals_compose::rollback::{self, Wording};
/// use std::path::Path;
///
/// # fn example(
/// #     command_line: &CommandLine,
/// #     directory: &Path,
/// # ) -> Result<(), rituals::Failure> {
/// // Needs a real project on disk, so this example is `no_run`.
/// let wording = Wording::project(directory, "running `cargo ritual remove lint` again");
/// let regenerated = rollback::attempt(wording, |changes| {
///     generated_file::regenerate_recording(changes, command_line, directory)
/// })?;
/// println!("{regenerated}");
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Regenerated {
    relative_path: PathBuf,
    outcome: WriteOutcome,
    imported: String,
}

impl std::fmt::Display for Regenerated {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let path = self.relative_path.display();
        match self.outcome {
            WriteOutcome::Created | WriteOutcome::Updated => {
                write!(formatter, "updated {path} ({})", self.imported)
            }
            WriteOutcome::UpToDate => {
                write!(
                    formatter,
                    "{path} is already up to date ({})",
                    self.imported
                )
            }
        }
    }
}

/// Names the tasks a generated file mounts, in the words of the manifest
/// list they came from: `tasks: ritual, hello`, or `no tasks`.
///
/// Named rather than counted: a count includes ritual's own bundle, so a
/// project with one task of its own would read `2 tasks`.
fn imported_label(entries: &[Entry]) -> String {
    if entries.is_empty() {
        return "no tasks".to_string();
    }
    let commands: Vec<&str> = entries.iter().map(Entry::command).collect();
    format!("tasks: {}", commands.join(", "))
}

/// Whether writing the generated file changed anything on disk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum WriteOutcome {
    /// The file did not exist and was created.
    Created,
    /// The file existed with different content and was rewritten.
    Updated,
    /// The file already held exactly this content; nothing was written.
    UpToDate,
}

/// Writes `content` to `path` on disk, replacing whatever is there.
fn write_to_disk(path: &Path, content: &str) -> Result<(), Failure> {
    std::fs::write(path, content).map_err(|error| io_failure("writing", path, error))
}

/// Writes `content` to `path` through `write` only if it differs from what
/// is already there, or if there is no file.
///
/// Comparing first is what makes `regenerate` idempotent at the filesystem
/// level, not just at the level of the bytes it would produce: running it
/// twice with no change in between must not even touch the file's
/// modification time, since a caller has no way to tell "rewritten with
/// identical content" from "left alone" apart from that.
///
/// The comparison lives here, once, so that the form that writes straight to
/// disk and the form that writes through a recorded run cannot disagree
/// about when a file counts as unchanged.
fn write_with(
    path: &Path,
    content: &str,
    write: impl FnOnce(&Path, &str) -> Result<(), Failure>,
) -> Result<WriteOutcome, Failure> {
    match std::fs::read_to_string(path) {
        Ok(existing) if existing == content => Ok(WriteOutcome::UpToDate),
        Ok(_existing) => {
            write(path, content)?;
            Ok(WriteOutcome::Updated)
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            write(path, content)?;
            Ok(WriteOutcome::Created)
        }
        Err(error) => Err(io_failure("reading", path, error)),
    }
}

/// Builds the [`Failure`] for an I/O error against `path`, naming which of
/// the two operations — `reading` or `writing` — failed.
fn io_failure(operation: &str, path: &Path, cause: std::io::Error) -> Failure {
    Failure::new(format!("{operation} {} failed", path.display())).caused_by(cause)
}

#[cfg(test)]
mod tests {
    use std::fs;

    use std::path::{Path, PathBuf};

    use rituals::{CommandLine, Failure, Identity, Name};

    use super::{
        Entry, TaskKey, WriteOutcome, regenerate_recording, render, write_to_disk, write_with,
    };
    use crate::rollback::{self, Wording};
    use crate::test_support::{ScratchDir, TestOutcome};

    /// A key that would hide a crate the generated file names is never a
    /// `TaskKey`, so no writer that takes one can put it in the list; any
    /// other usable name is, unchanged.
    #[test]
    fn a_task_key_is_never_made_from_std_or_core() -> TestOutcome {
        for hidden in ["std", "core"] {
            let refused = TaskKey::new(Name::new(hidden)?).map_err(|failure| failure.to_string());
            assert_eq!(
                refused,
                Err(format!(
                    "`{hidden}` would hide Rust's own `{hidden}` crate, which the generated \
                     command line is built on, and it would no longer compile; give this task \
                     another key"
                ))
            );
        }
        let key = TaskKey::new(Name::new("lint")?)?;
        assert_eq!(key.as_name(), &Name::new("lint")?);
        assert_eq!(key.to_string(), "lint");
        Ok(())
    }

    #[test]
    fn zero_entries_render_as_one_empty_array_line() {
        let rendered = render("ritual", &[]);
        assert!(rendered.contains("\n        [],\n"));
        assert!(!rendered.contains("        [\n"));
    }

    #[test]
    fn one_entry_renders_one_line_inside_the_array() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(rendered.contains("        [\n            (\"new\", new::task()),\n        ],\n"));
    }

    #[test]
    fn two_entries_render_in_the_given_order() {
        let rendered = render(
            "ritual",
            &[Entry::new("new", "new"), Entry::new("create", "create")],
        );
        assert!(rendered.contains(
            "        [\n            (\"new\", new::task()),\n            (\"create\", \
             create::task()),\n        ],\n"
        ));
    }

    #[test]
    fn three_entries_all_appear_in_order() {
        let rendered = render(
            "ritual",
            &[
                Entry::new("a", "a"),
                Entry::new("b", "b"),
                Entry::new("c", "c"),
            ],
        );
        let a_position = rendered.find("(\"a\", a::task())");
        let b_position = rendered.find("(\"b\", b::task())");
        let c_position = rendered.find("(\"c\", c::task())");
        // Each entry has to actually be present before its position means
        // anything — an entry `find` cannot locate returns `None`, and
        // comparing a missing position against `usize::MAX` would let a
        // dropped entry pass as "sorted last" instead of failing.
        assert!(a_position.is_some(), "entry a missing from rendered output");
        assert!(b_position.is_some(), "entry b missing from rendered output");
        assert!(c_position.is_some(), "entry c missing from rendered output");
        assert!(a_position < b_position, "expected a before b");
        assert!(b_position < c_position, "expected b before c");
    }

    #[test]
    fn a_keyword_extern_crate_gets_a_raw_identifier_and_nothing_else_does() {
        let rendered = render(
            "ritual",
            &[Entry::new("lint", "move"), Entry::new("check", "check")],
        );
        assert!(rendered.contains("(\"lint\", r#move::task()),"));
        assert!(rendered.contains("(\"check\", check::task()),"));
        assert_eq!(rendered.matches("r#").count(), 1);
    }

    #[test]
    fn rendering_twice_gives_the_same_bytes() {
        let entries = [Entry::new("new", "new"), Entry::new("create", "create")];
        assert_eq!(render("ritual", &entries), render("ritual", &entries));
    }

    #[test]
    fn the_first_line_is_the_generated_marker() {
        let rendered = render("ritual", &[]);
        assert!(rendered.starts_with("// @generated by ritual — do not edit.\n"));
    }

    #[test]
    fn the_rendered_file_names_the_identity_macro_exactly_once() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert_eq!(rendered.matches("rituals::identity!()").count(), 1);
    }

    #[test]
    fn the_rendered_file_never_names_the_composition_library() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(!rendered.contains("rituals_compose"));
    }

    #[test]
    fn the_rendered_file_contains_no_env_macro() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(!rendered.contains("env!("));
    }

    #[test]
    fn rendered_output_never_contains_an_asterisk() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(!rendered.contains('*'));
    }

    #[test]
    fn imported_label_names_every_task_in_manifest_order() {
        let entries = [Entry::new("ritual", "ritual"), Entry::new("hello", "hello")];
        assert_eq!(super::imported_label(&entries), "tasks: ritual, hello");
    }

    #[test]
    fn imported_label_names_a_single_task() {
        assert_eq!(
            super::imported_label(&[Entry::new("ritual", "ritual")]),
            "tasks: ritual"
        );
    }

    #[test]
    fn imported_label_says_so_when_nothing_is_imported() {
        assert_eq!(super::imported_label(&[]), "no tasks");
    }

    #[test]
    fn writing_to_a_missing_file_creates_it() -> TestOutcome {
        let scratch = ScratchDir::new("create")?;
        let path = scratch.path().join("main.rs");

        let outcome = write_with(&path, "content", write_to_disk)?;
        assert_eq!(outcome, WriteOutcome::Created);
        assert_eq!(fs::read_to_string(&path)?, "content");
        Ok(())
    }

    #[test]
    fn writing_different_content_updates_the_file() -> TestOutcome {
        let scratch = ScratchDir::new("update")?;
        let path = scratch.path().join("main.rs");
        fs::write(&path, "old")?;

        let outcome = write_with(&path, "new", write_to_disk)?;
        assert_eq!(outcome, WriteOutcome::Updated);
        assert_eq!(fs::read_to_string(&path)?, "new");
        Ok(())
    }

    #[test]
    fn writing_identical_content_reports_up_to_date_and_does_not_touch_the_file() -> TestOutcome {
        let scratch = ScratchDir::new("unchanged")?;
        let path = scratch.path().join("main.rs");
        fs::write(&path, "same")?;

        // Read-only, rather than a sleep-and-compare-mtimes check: on a
        // filesystem with coarse modification-time resolution, an
        // always-rewrite bug can still land on the same timestamp by
        // coincidence and pass. A read-only file turns an actual write
        // attempt into a hard failure instead.
        let mut permissions = fs::metadata(&path)?.permissions();
        permissions.set_readonly(true);
        fs::set_permissions(&path, permissions)?;

        // A process that ignores the read-only bit (root, on Unix) could
        // still write the file, which would make the assertion below pass
        // whether or not `write_with` skipped the write. This probe
        // opens for write without writing anything, so it tells the two cases
        // apart without disturbing the file's contents.
        let permission_is_enforced = fs::OpenOptions::new().write(true).open(&path).is_err();

        let outcome = if permission_is_enforced {
            Some(write_with(&path, "same", write_to_disk)?)
        } else {
            None
        };

        // Cleanup, on a scratch file this test alone created and is about
        // to delete — not a security boundary `set_readonly(false)`'s
        // world-writable warning is guarding here.
        let mut permissions = fs::metadata(&path)?.permissions();
        #[expect(
            clippy::permissions_set_readonly_false,
            reason = "restoring a scratch file's own permissions before removing it, not \
                      granting access to anything"
        )]
        {
            permissions.set_readonly(false);
        }
        fs::set_permissions(&path, permissions)?;

        let Some(outcome) = outcome else {
            crate::test_support::report_skip(
                "writing_identical_content_reports_up_to_date_and_does_not_touch_\
                     the_file could not demonstrate a blocked write because this process does \
                     not honour the read-only permission bit",
            );
            return Ok(());
        };
        assert_eq!(outcome, WriteOutcome::UpToDate);
        Ok(())
    }

    /// The text `src/main.rs` holds in a project whose task list is stale.
    const STALE_GENERATED_FILE: &str = "fn main() {}\n";

    /// A scratch project that `cargo metadata` can read without a network:
    /// a composed CLI crate called `demo-ritual` at the workspace root that
    /// imports one task, `hello`, by path, whose generated file does not yet
    /// mount it. Both depend on one `rituals`, a crate of that name beside
    /// them, as a task and the command line mounting it must. Returns the
    /// canonical workspace root, since `cargo metadata` reports the root it
    /// resolved and a temp directory may be behind a symbolic link.
    fn a_project_with_a_stale_generated_file(
        scratch: &ScratchDir,
    ) -> Result<PathBuf, std::io::Error> {
        let root = fs::canonicalize(scratch.path())?;
        fs::create_dir_all(root.join("src"))?;
        fs::create_dir_all(root.join("hello/src"))?;
        fs::create_dir_all(root.join("rituals/src"))?;
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"demo-ritual\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n\
             [package.metadata.ritual]\ntasks = [\"hello\"]\n\n\
             [dependencies]\nhello = { path = \"hello\" }\nrituals = { path = \"rituals\" }\n\n\
             [workspace]\n",
        )?;
        fs::write(root.join("src/main.rs"), STALE_GENERATED_FILE)?;
        fs::write(
            root.join("hello/Cargo.toml"),
            "[package]\nname = \"hello\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n\
             [dependencies]\nrituals = { path = \"../rituals\" }\n\n\
             [package.metadata.ritual]\ntask = true\n",
        )?;
        fs::write(root.join("hello/src/lib.rs"), "")?;
        fs::write(
            root.join("rituals/Cargo.toml"),
            "[package]\nname = \"rituals\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        )?;
        fs::write(root.join("rituals/src/lib.rs"), "")?;
        Ok(root)
    }

    fn the_demo_command_line() -> CommandLine {
        CommandLine::from_dispatch(
            Identity::from_macro_expansion("demo-ritual", "ritual", "0.1.0"),
            [],
            ["regenerate"],
        )
    }

    #[test]
    fn a_regeneration_through_changes_is_put_back_when_the_run_fails() -> TestOutcome {
        // Regenerates the stale file inside a run, then fails the run. The
        // generated file must be written while the run is going, and must
        // hold its old bytes afterwards; `Cargo.lock`, which `cargo metadata`
        // creates in a project that has none, must be gone again.
        let scratch = ScratchDir::new("regenerate-undone")?;
        let root = a_project_with_a_stale_generated_file(&scratch)?;
        let generated = root.join("src/main.rs");
        let lockfile = root.join("Cargo.lock");
        let command_line = the_demo_command_line();

        let mut seen_inside_the_run = String::new();
        let failure = rollback::attempt(
            Wording::project(&root, "running `cargo ritual remove hello` again"),
            |changes| {
                regenerate_recording(changes, &command_line, &root)?;
                seen_inside_the_run = fs::read_to_string(&generated)
                    .map_err(|error| Failure::new("reading the generated file").caused_by(error))?;
                Err::<(), _>(Failure::new("a later step failed"))
            },
        )
        .err()
        .ok_or("the run was meant to fail")?;

        assert!(
            seen_inside_the_run.contains("(\"hello\", hello::task()),"),
            "the generated file was not rewritten during the run: {seen_inside_the_run}"
        );
        assert_eq!(fs::read_to_string(&generated)?, STALE_GENERATED_FILE);
        assert!(
            !lockfile.exists(),
            "the lockfile the fetch created was kept"
        );
        assert!(
            failure
                .to_string()
                .ends_with("ritual put the project back as it found it"),
            "failure was: {failure}"
        );
        Ok(())
    }

    #[test]
    fn a_successful_regeneration_through_changes_keeps_the_file() -> TestOutcome {
        let scratch = ScratchDir::new("regenerate-kept")?;
        let root = a_project_with_a_stale_generated_file(&scratch)?;
        let command_line = the_demo_command_line();

        let regenerated = rollback::attempt(
            Wording::project(&root, "running `cargo ritual remove hello` again"),
            |changes| regenerate_recording(changes, &command_line, &root),
        )?;

        let expected = render("demo-ritual", &[Entry::new("hello", "hello")]);
        assert_eq!(fs::read_to_string(root.join("src/main.rs"))?, expected);
        assert_eq!(
            regenerated.to_string(),
            "updated src/main.rs (tasks: hello)"
        );
        Ok(())
    }

    #[test]
    fn an_unchanged_generated_file_is_not_written_through_changes() -> TestOutcome {
        // The second regeneration finds the file already current, so it must
        // not write: with the file read-only, a write would fail the run.
        let scratch = ScratchDir::new("regenerate-unchanged")?;
        let root = a_project_with_a_stale_generated_file(&scratch)?;
        let generated = root.join("src/main.rs");
        let command_line = the_demo_command_line();
        rollback::attempt(
            Wording::project(&root, "running `cargo ritual remove hello` again"),
            |changes| regenerate_recording(changes, &command_line, &root),
        )?;

        let mut permissions = fs::metadata(&generated)?.permissions();
        permissions.set_readonly(true);
        fs::set_permissions(&generated, permissions)?;
        // See `writing_identical_content_reports_up_to_date_and_does_not_touch_the_file`:
        // a process that ignores the read-only bit cannot show a blocked write.
        let permission_is_enforced = fs::OpenOptions::new().write(true).open(&generated).is_err();

        let regenerated = if permission_is_enforced {
            Some(rollback::attempt(
                Wording::project(&root, "running `cargo ritual remove hello` again"),
                |changes| regenerate_recording(changes, &command_line, &root),
            ))
        } else {
            None
        };

        let mut permissions = fs::metadata(&generated)?.permissions();
        #[expect(
            clippy::permissions_set_readonly_false,
            reason = "restoring a scratch file's own permissions before removing it, not \
                      granting access to anything"
        )]
        {
            permissions.set_readonly(false);
        }
        fs::set_permissions(&generated, permissions)?;

        let Some(regenerated) = regenerated else {
            crate::test_support::report_skip(
                "an_unchanged_generated_file_is_not_written_through_changes could not \
                 demonstrate a blocked write because this process does not honour the \
                 read-only permission bit",
            );
            return Ok(());
        };
        assert_eq!(
            regenerated?.to_string(),
            "src/main.rs is already up to date (tasks: hello)"
        );
        Ok(())
    }

    #[test]
    fn regenerated_displays_the_line_regenerate_reports_for_both_outcomes() -> TestOutcome {
        let scratch = ScratchDir::new("regenerate-display")?;
        let root = a_project_with_a_stale_generated_file(&scratch)?;
        let command_line = the_demo_command_line();
        let regenerate_once = || {
            rollback::attempt(
                Wording::project(&root, "running `cargo ritual remove hello` again"),
                |changes| regenerate_recording(changes, &command_line, &root),
            )
        };

        assert_eq!(
            regenerate_once()?.to_string(),
            "updated src/main.rs (tasks: hello)"
        );
        assert_eq!(
            regenerate_once()?.to_string(),
            "src/main.rs is already up to date (tasks: hello)"
        );
        Ok(())
    }

    #[test]
    fn a_regeneration_from_a_members_directory_puts_back_the_workspaces_lockfile() -> TestOutcome {
        // `cargo metadata` run from a member's directory writes the
        // workspace root's `Cargo.lock`, not one in the member's directory.
        // The project has none, so a run that fails must leave none at the
        // root, and must not leave one in the member's directory either.
        let scratch = ScratchDir::new("regenerate-from-member")?;
        let root = a_project_with_a_stale_generated_file(&scratch)?;
        let command_line = the_demo_command_line();
        let member_directory: &Path = &root.join("hello");

        let failure = rollback::attempt(
            Wording::project(&root, "running `cargo ritual remove hello` again"),
            |changes| {
                regenerate_recording(changes, &command_line, member_directory)?;
                Err::<(), _>(Failure::new("a later step failed"))
            },
        )
        .err()
        .ok_or("the run was meant to fail")?;

        assert_eq!(
            failure.to_string(),
            "a later step failed; ritual put the project back as it found it"
        );
        assert!(
            !root.join("Cargo.lock").exists(),
            "the workspace's lockfile the fetch created was kept"
        );
        assert!(!member_directory.join("Cargo.lock").exists());
        assert_eq!(
            fs::read_to_string(root.join("src/main.rs"))?,
            STALE_GENERATED_FILE
        );
        Ok(())
    }
}
