//! The composed command line's one generated file: what goes in it, what it
//! says, and the operation that rewrites it.
//!
//! `render` is the text this file always starts and ends with — the `//
//! @generated` banner, one `("<name>", <crate>::task())` line per imported
//! task, and the call into `rituals::run`. `write_if_changed` writes that text
//! only when it actually differs from what is already on disk, which is what
//! makes running the operation twice with nothing changed in between leave the
//! file's own modification time untouched, not merely its bytes unchanged.

mod entry;
mod identifier;

use std::fmt::Write as _;
use std::path::Path;

pub use entry::Entry;
use identifier::render_identifier;
use rituals::{CommandLine, Failure, Outcome, report};

use crate::{metadata, top_level};

/// Renders a composed command line's generated `main.rs`.
///
/// `package_name` names the composed CLI crate this file belongs to — it
/// appears only in the module doc comment; the rest of the file reads its
/// own identity — package name, bin name and version — from
/// `rituals::identity!()` at compile time. `entries` are emitted in
/// the order given, one per line, with no wrapping and no sorting: the order
/// is the caller's, because it is the order
/// `[package.metadata.ritual] tasks = [...]` names them in, and keeping the
/// two in step is what makes a diff of the generated file boring.
///
/// The rendered file names `rituals` and nothing else — a composed CLI
/// crate depends on the framework crate directly, not on this one.
///
/// # Examples
///
/// ```
/// use rituals_compose::generated_file::{Entry, render};
///
/// let rendered = render("rituals-cli", &[Entry::new("new", "new")]);
/// assert!(rendered.starts_with("// @generated by ritual — do not edit.\n"));
/// assert!(rendered.contains("    rituals::run(\n"));
/// assert!(rendered.contains("            (\"new\", new::task()),\n"));
/// ```
#[must_use]
pub fn render(package_name: &str, entries: &[Entry]) -> String {
    let mut output = String::new();

    output.push_str("// @generated by ritual — do not edit.\n");
    output.push_str("//\n");
    output.push_str(
        "// Every task named in [package.metadata.ritual] tasks in this crate's Cargo.toml\n",
    );
    output
        .push_str("// is handed to the framework below. Change that list, then run this command\n");
    output.push_str("// line's `regenerate` task.\n");
    output.push_str("//\n");
    output.push_str(
        "// If this file stopped compiling because a task's dependency was removed before\n",
    );
    output.push_str(
        "// its entry was dropped from that list: put the dependency back, drop the entry,\n",
    );
    output.push_str("// run `regenerate`, then remove the dependency.\n");
    output.push('\n');
    // A String's Write impl never returns Err, so the result is discarded
    // deliberately rather than propagated.
    let _ = writeln!(output, "//! The composed `{package_name}` command line.");
    output.push('\n');
    output.push_str(
        "// rustfmt is skipped here on purpose: this file has to be reproducible byte for\n",
    );
    output.push_str(
        "// byte, and that is only true while one thing decides its formatting. Predicting\n",
    );
    output.push_str("// where rustfmt breaks a line is a moving target, not a contract.\n");
    output.push_str("#[rustfmt::skip]\n");
    output.push_str("fn main() -> std::process::ExitCode {\n");
    output.push_str("    rituals::run(\n");
    output.push_str("        rituals::identity!(),\n");
    render_entries(&mut output, entries);
    output.push_str("    )\n");
    output.push_str("}\n");

    output
}

/// Appends the second argument to `rituals::run` — an empty array on
/// one line, or one indented entry per line — to `output`.
fn render_entries(output: &mut String, entries: &[Entry]) {
    if entries.is_empty() {
        output.push_str("        [],\n");
        return;
    }

    output.push_str("        [\n");
    for entry in entries {
        let identifier = render_identifier(&entry.extern_crate);
        let _ = writeln!(
            output,
            "            (\"{}\", {identifier}::task()),",
            entry.command
        );
    }
    output.push_str("        ],\n");
}

/// Rewrites `command_line`'s composed CLI's generated file from its current
/// imports, reporting what it did.
///
/// The whole operation: read the current directory, fetch the resolved
/// dependency graph, resolve the task list and locate the project on it,
/// [`render`] the text, and write it if it changed. Lives here, beside
/// [`render`], rather than in either task that calls it — both `add` and
/// `regenerate` run this same path, and neither can depend on the other, so
/// the one place both can reach it without a dependency between them is the
/// module that already renders the file both act on. `render` is the text;
/// this is the operation; `new` is the caller that genuinely wants only the
/// first, for a fresh project's generated file before it has any imports at
/// all.
///
/// Takes the whole [`CommandLine`] rather than a package name: in this
/// repository's own composed CLI, the package is `rituals-cli` and the bin
/// is `ritual`, so a bare `&str` parameter would accept the wrong one
/// silently. And `regenerate` is one of the two writing tasks that has to
/// weigh a name it is about to write against the *running* command line's
/// own top level, not only against this project's manifest — the same
/// commands its own identity's package name cannot answer alone — so it
/// needs the whole command line, not only the identity inside it.
///
/// # Errors
///
/// Returns a [`rituals::Failure`] naming whichever step failed: reading the
/// current directory, fetching or resolving the metadata, a task name that
/// is already a top-level command of `command_line`, or reading or writing
/// the file.
///
/// # Examples
///
/// ```
/// use rituals::{CommandLine, Outcome, Task, clap};
/// use rituals_compose::generated_file;
///
/// /// Rewrites this project's generated file from its current imports.
/// #[derive(clap::Args)]
/// struct Arguments {}
///
/// fn run(command_line: &CommandLine, _arguments: Arguments) -> Outcome {
///     generated_file::regenerate(command_line)
/// }
///
/// // Never invoked here: running it needs a real project on disk and a
/// // `cargo metadata` call. This shows the whole of a task built on it.
/// let _task = Task::receiving_command_line("rewrite the generated task list", run);
/// ```
pub fn regenerate(command_line: &CommandLine) -> Outcome {
    let package_name = command_line.identity().package_name();

    let current_dir = std::env::current_dir()
        .map_err(|error| Failure::new("reading the current directory failed").caused_by(error))?;
    let document = metadata::fetch(&current_dir)?;

    document.ensure_runs_in_its_own_project(package_name, "regenerate", "")?;
    let entries = document.resolve_task_list(package_name)?;
    for entry in &entries {
        top_level::ensure_command_is_free(command_line, entry.command())?;
    }
    let project = document.locate_project(package_name)?;

    let rendered = render(package_name, &entries);
    let outcome = write_if_changed(project.binary_src_path, &rendered)?;

    let relative_path = project
        .binary_src_path
        .strip_prefix(project.workspace_root())
        .unwrap_or(project.binary_src_path);
    let imported = imported_label(&entries);

    match outcome {
        WriteOutcome::Created | WriteOutcome::Updated => {
            report(format!("updated {} ({imported})", relative_path.display()));
        }
        WriteOutcome::UpToDate => {
            report(format!(
                "{} is already up to date ({imported})",
                relative_path.display()
            ));
        }
    }

    Ok(())
}

/// Names the tasks a generated file mounts, in the words of the manifest
/// list they came from: `tasks: ritual, hello`, or `no tasks`.
///
/// Named rather than counted: a count includes ritual's own bundle, so a
/// project with one task of its own would read `2 tasks`.
fn imported_label(entries: &[Entry]) -> String {
    if entries.is_empty() {
        return "no tasks".to_string();
    }
    let commands: Vec<&str> = entries.iter().map(Entry::command).collect();
    format!("tasks: {}", commands.join(", "))
}

/// Whether writing the generated file changed anything on disk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum WriteOutcome {
    /// The file did not exist and was created.
    Created,
    /// The file existed with different content and was rewritten.
    Updated,
    /// The file already held exactly this content; nothing was written.
    UpToDate,
}

/// Writes `content` to `path` only if it differs from what is already
/// there.
///
/// Comparing first is what makes `regenerate` idempotent at the filesystem
/// level, not just at the level of the bytes it would produce: running it
/// twice with no change in between must not even touch the file's
/// modification time, since a caller has no way to tell "rewritten with
/// identical content" from "left alone" apart from that.
///
/// # Errors
///
/// Returns a [`Failure`] naming `path` when reading the existing file (for
/// a reason other than it not existing) or writing the new content fails.
pub(crate) fn write_if_changed(path: &Path, content: &str) -> Result<WriteOutcome, Failure> {
    match std::fs::read_to_string(path) {
        Ok(existing) if existing == content => Ok(WriteOutcome::UpToDate),
        Ok(_existing) => {
            std::fs::write(path, content).map_err(|error| io_failure("writing", path, error))?;
            Ok(WriteOutcome::Updated)
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            std::fs::write(path, content).map_err(|error| io_failure("writing", path, error))?;
            Ok(WriteOutcome::Created)
        }
        Err(error) => Err(io_failure("reading", path, error)),
    }
}

/// Builds the [`Failure`] for an I/O error against `path`, naming which of
/// the two operations — `reading` or `writing` — failed.
fn io_failure(operation: &str, path: &Path, cause: std::io::Error) -> Failure {
    Failure::new(format!("{operation} {} failed", path.display())).caused_by(cause)
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::{Entry, WriteOutcome, render, write_if_changed};
    use crate::test_support::{ScratchDir, TestOutcome};

    #[test]
    fn zero_entries_render_as_one_empty_array_line() {
        let rendered = render("ritual", &[]);
        assert!(rendered.contains("\n        [],\n"));
        assert!(!rendered.contains("        [\n"));
    }

    #[test]
    fn one_entry_renders_one_line_inside_the_array() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(rendered.contains("        [\n            (\"new\", new::task()),\n        ],\n"));
    }

    #[test]
    fn two_entries_render_in_the_given_order() {
        let rendered = render(
            "ritual",
            &[Entry::new("new", "new"), Entry::new("create", "create")],
        );
        assert!(rendered.contains(
            "        [\n            (\"new\", new::task()),\n            (\"create\", \
             create::task()),\n        ],\n"
        ));
    }

    #[test]
    fn three_entries_all_appear_in_order() {
        let rendered = render(
            "ritual",
            &[
                Entry::new("a", "a"),
                Entry::new("b", "b"),
                Entry::new("c", "c"),
            ],
        );
        let a_position = rendered.find("(\"a\", a::task())");
        let b_position = rendered.find("(\"b\", b::task())");
        let c_position = rendered.find("(\"c\", c::task())");
        // Each entry has to actually be present before its position means
        // anything — an entry `find` cannot locate returns `None`, and
        // comparing a missing position against `usize::MAX` would let a
        // dropped entry pass as "sorted last" instead of failing.
        assert!(a_position.is_some(), "entry a missing from rendered output");
        assert!(b_position.is_some(), "entry b missing from rendered output");
        assert!(c_position.is_some(), "entry c missing from rendered output");
        assert!(a_position < b_position, "expected a before b");
        assert!(b_position < c_position, "expected b before c");
    }

    #[test]
    fn a_keyword_extern_crate_gets_a_raw_identifier_and_nothing_else_does() {
        let rendered = render(
            "ritual",
            &[Entry::new("lint", "move"), Entry::new("check", "check")],
        );
        assert!(rendered.contains("(\"lint\", r#move::task()),"));
        assert!(rendered.contains("(\"check\", check::task()),"));
        assert_eq!(rendered.matches("r#").count(), 1);
    }

    #[test]
    fn rendering_twice_gives_the_same_bytes() {
        let entries = [Entry::new("new", "new"), Entry::new("create", "create")];
        assert_eq!(render("ritual", &entries), render("ritual", &entries));
    }

    #[test]
    fn the_first_line_is_the_generated_marker() {
        let rendered = render("ritual", &[]);
        assert!(rendered.starts_with("// @generated by ritual — do not edit.\n"));
    }

    #[test]
    fn the_rendered_file_names_the_identity_macro_exactly_once() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert_eq!(rendered.matches("rituals::identity!()").count(), 1);
    }

    #[test]
    fn the_rendered_file_never_names_the_composition_library() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(!rendered.contains("rituals_compose"));
    }

    #[test]
    fn the_rendered_file_contains_no_env_macro() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(!rendered.contains("env!("));
    }

    #[test]
    fn rendered_output_never_contains_an_asterisk() {
        let rendered = render("ritual", &[Entry::new("new", "new")]);
        assert!(!rendered.contains('*'));
    }

    #[test]
    fn imported_label_names_every_task_in_manifest_order() {
        let entries = [Entry::new("ritual", "ritual"), Entry::new("hello", "hello")];
        assert_eq!(super::imported_label(&entries), "tasks: ritual, hello");
    }

    #[test]
    fn imported_label_names_a_single_task() {
        assert_eq!(
            super::imported_label(&[Entry::new("ritual", "ritual")]),
            "tasks: ritual"
        );
    }

    #[test]
    fn imported_label_says_so_when_nothing_is_imported() {
        assert_eq!(super::imported_label(&[]), "no tasks");
    }

    #[test]
    fn writing_to_a_missing_file_creates_it() -> TestOutcome {
        let scratch = ScratchDir::new("create")?;
        let path = scratch.path().join("main.rs");

        let outcome = write_if_changed(&path, "content")?;
        assert_eq!(outcome, WriteOutcome::Created);
        assert_eq!(fs::read_to_string(&path)?, "content");
        Ok(())
    }

    #[test]
    fn writing_different_content_updates_the_file() -> TestOutcome {
        let scratch = ScratchDir::new("update")?;
        let path = scratch.path().join("main.rs");
        fs::write(&path, "old")?;

        let outcome = write_if_changed(&path, "new")?;
        assert_eq!(outcome, WriteOutcome::Updated);
        assert_eq!(fs::read_to_string(&path)?, "new");
        Ok(())
    }

    #[test]
    fn writing_identical_content_reports_up_to_date_and_does_not_touch_the_file() -> TestOutcome {
        let scratch = ScratchDir::new("unchanged")?;
        let path = scratch.path().join("main.rs");
        fs::write(&path, "same")?;

        // Read-only, rather than a sleep-and-compare-mtimes check: on a
        // filesystem with coarse modification-time resolution, an
        // always-rewrite bug can still land on the same timestamp by
        // coincidence and pass. A read-only file turns an actual write
        // attempt into a hard failure instead.
        let mut permissions = fs::metadata(&path)?.permissions();
        permissions.set_readonly(true);
        fs::set_permissions(&path, permissions)?;

        // A process that ignores the read-only bit (root, on Unix) could
        // still write the file, which would make the assertion below pass
        // whether or not `write_if_changed` skipped the write. This probe
        // opens for write without writing anything, so it tells the two cases
        // apart without disturbing the file's contents.
        let permission_is_enforced = fs::OpenOptions::new().write(true).open(&path).is_err();

        let outcome = if permission_is_enforced {
            Some(write_if_changed(&path, "same")?)
        } else {
            None
        };

        // Cleanup, on a scratch file this test alone created and is about
        // to delete — not a security boundary `set_readonly(false)`'s
        // world-writable warning is guarding here.
        let mut permissions = fs::metadata(&path)?.permissions();
        #[expect(
            clippy::permissions_set_readonly_false,
            reason = "restoring a scratch file's own permissions before removing it, not \
                      granting access to anything"
        )]
        {
            permissions.set_readonly(false);
        }
        fs::set_permissions(&path, permissions)?;

        let Some(outcome) = outcome else {
            crate::test_support::report_skip(
                "writing_identical_content_reports_up_to_date_and_does_not_touch_\
                     the_file could not demonstrate a blocked write because this process does \
                     not honour the read-only permission bit",
            );
            return Ok(());
        };
        assert_eq!(outcome, WriteOutcome::UpToDate);
        Ok(())
    }
}
